In [1]:
import torch
import numpy as np

# Tensor 초기화

In [6]:
# 데이터로부터 직접 생성
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

# Numpy 배열로부터 생성
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# 다른 텐서로부터 생성
# 명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성을 유지
x_ones = torch.ones_like(x_data)  # x_data의 속성 유지
print(f"Ones Tensor : \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성 덮어씀
print(f"Random Tensor: \n {x_rand} \n")

# 무작위(random) 또는 상수(constant) 값을 사용
# shape은 텐서의 차원(dimension)을 나타내는 튜플(tuple)로, 아래 함수들에서는 출력 텐서의 차원을 결정
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7660, 0.0618],
        [0.2063, 0.2943]]) 

Random Tensor: 
 tensor([[0.9133, 0.5194, 0.1928],
        [0.5531, 0.2183, 0.5646]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



# 텐서의 속성(Attribute)
- 텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타냄

In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# 텐서 연산(Operation)
- 각 연산들은 (일반적으로 CPU보다 빠른) GPU에서 실행할 수 있습니다.

- 기본적으로 텐서는 CPU에 생성됩니다. .to 메소드를 사용하면 (GPU의 가용성(availability)을 확인한 뒤) GPU로 텐서를 명시적으로 이동할 수 있습니다. 

- 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이든다는 것을 기억하세요!

In [8]:
# GPU가 존재하면 텐서를 이동
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [10]:
# Numpy식의 표준 인덱싱과 슬라이싱:
tensor = torch.ones(4,4)
print('First row: ', tensor[0])
print('First columns: ', tensor[:, 0])
print('Last columns: ', tensor[..., -1])

tensor[:, 1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First columns:  tensor([1., 1., 1., 1.])
Last columns:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
# 텐서 합치기
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [14]:
## 산술 연산(Arithmetic operations)
# 두 텐서 간의 행렬 곱(matrix multiplication) - 모두 동일한 값
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [15]:
# 단일-요소(single-element) 텐서
# 텐서의 모든 값으 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우, python 숫자 값으로 변환
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [16]:
# 바꿔치기(in-place) 연산 - 연산 결과를 피연산자(operand)에 저장하는 연산 (_ 접미사 있음 주의)

# 바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있습니다. 
# 따라서, 사용을 권장하지 않습니다.
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Numpy 변환(Bridge)
- CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

## 텐서를 Numpy 배열로 변환

In [18]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [19]:
# 텐서의 변경사항이 Numpy 배열에 반영
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## Numpy 배열을 텐서로 변환

In [20]:
n = np.ones(5)
t = torch.from_numpy(n)

In [21]:
# Numpy 배열의 변경 사항이 텐서에 반영
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
