In [2]:
import numpy as np
import torch

In [9]:
print(torch.cuda.get_device_name(0))
print(torch.cuda.is_available())
print(torch.__version__)

NVIDIA GeForce RTX 2060 SUPER
True
1.10.1+cu102


## Numpy Review
### 1D Array with Numpy

In [15]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])   # Slicing
print('t[:2] t[3:]     = ', t[:2], t[3:])      # Slicing

[0. 1. 2. 3. 4. 5. 6.]
Rank  of t:  1
Shape of t:  (7,)
t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


### 2D Array with Numpy

In [19]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank  of t:  2
Shape of t:  (4, 3)


## PyTorch is like NumPy (but better)
### 1D Array with PyTorch

In [22]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

print(t.dim())  # rank
print(t.shape)  # shape
print(t.size()) # shape
print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D Array with PyTorch

In [24]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

print(t.dim())  # rank
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Frequently Used Operations in PyTorch

### Broadcasting
- 텐서 간의 크기가 맞지 않아도 자동적으로 사이즈 맞춰서 계산 가능함

In [30]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [31]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [32]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # (1,2) -> (2,2)
m2 = torch.FloatTensor([[3], [4]]) # (2,1) -> (2,2)
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### Mul(Multiplication, 원소 별 곱셈) vs. Matmul(Matrix Multiplication, 행렬 곱셈)

In [28]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(m1)
print(m2)
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1


tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])


In [29]:
# 행렬 곱
print(m1.matmul(m2)) # (2,1)

# 원소별 곱
print(m1 * m2) # (2,2) = (2,2) x (2,2)
print(m1.mul(m2))

tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Mean

In [33]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [34]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

mean(): input dtype should be either floating point or complex dtypes. Got Long instead.


In [35]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.mean()) # 전체 평균
print(t.mean(dim=0)) # 열 별
print(t.mean(dim=1)) # 행 별
print(t.mean(dim=-1)) # 두번째 차원을 제거. 즉, 열이 제거된 텐서 (2,2) -> (2,1)

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum

In [36]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [37]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and Argmax

In [38]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [41]:
print(t.max()) # Returns one value: max

tensor(4.)


In [43]:
print(t.max(dim=0)) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [44]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [46]:
print(t.max(dim=1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [47]:
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### View(Reshape)

In [3]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [4]:
print(ft.view([-1, 3])) 
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [5]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze
- 1인 차원을 제거
- 차원을 지정해주어도 1이 아니면 변화 없음

In [6]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [7]:
print(ft.squeeze())
print(ft.squeeze().shape) # (3,1) -> (3,)

tensor([0., 1., 2.])
torch.Size([3])


###  Unsqeeze

In [8]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape) # (3,)

torch.Size([3])


In [9]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape) # (1,3)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [10]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape) # (1,3)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [12]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape) # (3,1)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [13]:
print(ft.unsqueeze(-1)) # dim=-1 : 마지막 dimension 의미 (dim=1)
print(ft.unsqueeze(-1).shape) # (3,1)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Type Casting

In [15]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [17]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenation

In [18]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [19]:
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

In [20]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [21]:
print(torch.stack([x, y, z])) # (3,2)
print(torch.stack([x, y, z], dim=1)) # (2,3)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [22]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros

In [23]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [24]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [29]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [30]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [31]:
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


### Scatter (for one-hot encoding)

In [32]:
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [33]:
one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1)
print(one_hot)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


## Miscellaneous

### Zip

In [34]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [35]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
